name=Arduino-SIA-DC-09
version=1.0.0
author=Anirudh M.B.
maintainer=Anirudh M.B.
sentence=Library for composing and parsing, and also sending and receiving messages for the SIA DC-09 protocol.
paragraph=Library for composing and parsing, and also sending and receiving messages for the SIA DC-09 protocol.
category=Communication
url=https://github.com/DawnGuardian/Arduino-SIA-DC-09
architectures=*